services:
  abrat:
    build: .
    container_name: my-abrat-app
    ports:
      - "8501:8501"
    volumes:
      #- ./data:/app/data
      - .:/app # mounted einfach alles - später entfernen
      #- ./abrat:/app/abrat # Mounten des abrat-Ordners für Live-Updates - später entfernen
      #- ./content:/app/content # Mounten des content-Ordners für Live-Updates - später entfernen
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped